import type { Metadata } from 'next';
import { Inter, Lusitana } from 'next/font/google';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import './ui/globals.css';
import 'sanitize.css';
import { AuthProvider } from './provider/AuthProvider';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <AppRouterCacheProvider>
        <html lang="ja">
          <body className={`${inter.className} antialiased`}>
            {children}
          </body>
        </html>
      </AppRouterCacheProvider>
    </AuthProvider>
  );
}
